name: Tests

on: [push, pull_request]

jobs:
  build-release:
    name: Build Linux Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup environment
        shell: bash
        run: echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.2'
      
      - name: Build Proxi
        run: |
          cd proxi
          go install

      - name: Upload Proxi build to GitHub 
        uses: actions/upload-artifact@v4
        with: 
          name: proxi-${{ env.SHORT_SHA }}
          path: ~/go/bin/proxi